"""Run with python -m backend.radar_v3.server. Reads real ODIM volumes on disk."""
import gzip
import hashlib
import json
import logging
import os
from pathlib import Path
import re
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs
from .odim import read_volume

LOG = logging.getLogger('BRASIL-SCOPE-V3')
SAFE = re.compile(r'^[a-z0-9_-]{1,64}$')

class Store:
    def __init__(self, root, cache, cptec=False):
        self.root, self.cache = Path(root).resolve(), Path(cache).resolve()
        self.cache.mkdir(parents=True, exist_ok=True)
        self.lock = threading.Lock()  # One decoded volume in RAM at a time.
        self.cptec = None
        if cptec:
            from .adapters.cptec import Adapter
            self.cptec = Adapter(self.cache)

    def prune_cache(self):
        # Only files generated by this service, within the resolved cache directory.
        files=sorted((p for p in self.cache.iterdir() if re.fullmatch(r'[a-f0-9]{64}\.(?:bin\.gz|png)',p.name)),key=lambda p:p.stat().st_mtime,reverse=True)
        total=0
        for path in files:
            stat=path.stat();total+=stat.st_size
            if time.time()-stat.st_mtime>48*3600 or total>256*1024*1024:
                path.unlink(missing_ok=True)
                path.with_name(path.name.split('.')[0]+'.json').unlink(missing_ok=True)

    def radars(self):
        result=[]
        if self.root.exists():
            for p in sorted(self.root.iterdir()):
                if p.is_dir() and SAFE.fullmatch(p.name) and any(p.glob('*.h5')):
                    available=[product for product in ('reflectivity','velocity') if self.frames(p.name,product)]
                    result.append(dict(id=p.name,name=p.name.replace('-',' ').title(),source='Volume polar',products=available))
        if self.cptec:
            result += [{k:v for k,v in r.items() if k!='codes'} for r in self.cptec.radars()]
        return result

    def products(self, radar):
        available=[]; latest={}
        for product in ('reflectivity','velocity'):
            frames=self.frames(radar,product)
            if frames: available.append(product);latest[product]=frames[-1]['timestamp']
        return dict(radar=radar,products=available,latest=latest)

    def frames(self, radar, product):
        if not SAFE.fullmatch(radar) or product not in ('reflectivity','velocity'): raise ValueError('Radar ou produto inválido')
        # Local polar products always have priority over official rendered products.
        if self.cptec and radar.startswith('cptec-') and not any((self.root/radar).glob('*.h5')):
            with self.lock: self.prune_cache()
            return self.cptec.frames(radar,product)
        directory = (self.root/radar).resolve()
        if not directory.is_relative_to(self.root): raise ValueError('Radar inválido')
        provider='odim';reader=read_volume
        manifest=directory/'radar.json'
        if manifest.exists() and json.loads(manifest.read_text('utf-8')).get('source')=='CEMADEN':
            from .adapters.cemaden import read
            provider='cemaden';reader=read
        frames = []
        with self.lock:
            self.prune_cache()
            # Bound discovery work; source volume retention is controlled by its owner.
            files = sorted(directory.glob('*.h5'), key=lambda p:p.stat().st_mtime, reverse=True)[:576]
            for path in files:
                stat = path.stat()
                key = hashlib.sha256(f'{provider}-v2:{radar}:{path}:{stat.st_size}:{stat.st_mtime_ns}:{product}'.encode()).hexdigest()
                meta_path, binary_path = self.cache/f'{key}.json', self.cache/f'{key}.bin.gz'
                if meta_path.exists() and binary_path.exists():
                    metadata = json.loads(meta_path.read_text('utf-8'))
                else:
                    try: metadata, binary = reader(path, radar, product)
                    except LookupError: continue
                    except (ValueError, KeyError, OSError):
                        LOG.warning('[RADAR-ERROR] Volume rejeitado: %s', path.name); continue
                    metadata['frameId'] = key
                    temporary = binary_path.with_suffix('.tmp')
                    temporary.write_bytes(gzip.compress(binary, compresslevel=5)); temporary.replace(binary_path)
                    temporary = meta_path.with_suffix('.tmp')
                    temporary.write_text(json.dumps(metadata, ensure_ascii=False), encoding='utf-8'); temporary.replace(meta_path)
                    LOG.info('[RADAR-CACHE] %s %s %s', radar, product, metadata['timestamp'])
                frames.append(metadata)
        if not frames and self.cptec and radar.startswith('cptec-'): return self.cptec.frames(radar,product)
        return sorted(frames, key=lambda m:m['timestamp'])

def handler_for(store):
    class Handler(BaseHTTPRequestHandler):
        def end_headers(self):
            origin = self.headers.get('Origin',''); parsed = urlparse(origin)
            allowed = set(os.environ.get('RADAR_V3_ORIGINS','https://sideralmeteorologiabrasil.web.app').split(','))
            if origin in allowed or (parsed.scheme=='http' and parsed.hostname in ('localhost','127.0.0.1')):
                self.send_header('Access-Control-Allow-Origin', origin)
                self.send_header('Vary','Origin')
            self.send_header('X-Content-Type-Options','nosniff')
            super().end_headers()

        def reply(self, data, status=200):
            body = json.dumps(data, ensure_ascii=False).encode()
            self.send_response(status); self.send_header('Content-Type','application/json; charset=utf-8')
            self.send_header('Cache-Control','no-store'); self.send_header('Content-Length',str(len(body)))
            self.end_headers(); self.wfile.write(body)

        def do_OPTIONS(self):
            self.send_response(204); self.send_header('Access-Control-Allow-Methods','GET, OPTIONS')
            self.send_header('Access-Control-Allow-Headers','Content-Type'); self.end_headers()

        def do_GET(self):
            route = urlparse(self.path); query = parse_qs(route.query)
            try:
                if route.path in ('/health','/api/radar/v3/health'): return self.reply(dict(status='ok', service='Brasil Scope V3'))
                if route.path == '/api/radar/v3/radars': return self.reply(dict(radars=store.radars()))
                if route.path == '/api/radar/v3/products': return self.reply(store.products(query.get('radar',[''])[0]))
                if route.path == '/api/radar/v3/image':
                    key=query.get('id',[''])[0]
                    if not re.fullmatch('[a-f0-9]{64}',key): raise ValueError('Quadro inválido')
                    path=store.cache/(key+'.png')
                    if not path.exists(): return self.reply(dict(error='Quadro indisponível'),404)
                    body=path.read_bytes();self.send_response(200)
                    self.send_header('Content-Type','image/png');self.send_header('Cache-Control','public, max-age=86400, immutable')
                    self.send_header('Content-Length',str(len(body)));self.end_headers();self.wfile.write(body);return
                if route.path == '/api/radar/v3/metadata' and 'id' in query:
                    key = query['id'][0]
                    if not re.fullmatch('[a-f0-9]{64}',key): raise ValueError('Quadro inválido')
                    path = store.cache/f'{key}.json'
                    if not path.exists(): return self.reply(dict(error='Quadro indisponível'),404)
                    metadata = json.loads(path.read_text('utf-8'))
                    if metadata.get('kind')=='raster': metadata.pop('legendUrl',None)
                    if metadata.get('kind')!='raster': metadata['dataUrl'] = '/api/radar/v3/data?id='+key
                    return self.reply(metadata)
                if route.path == '/api/radar/v3/data':
                    key = query.get('id',[''])[0]
                    if not re.fullmatch('[a-f0-9]{64}',key): raise ValueError('Quadro inválido')
                    path = store.cache/f'{key}.bin.gz'
                    if not path.exists(): return self.reply(dict(error='Quadro indisponível'),404)
                    body = path.read_bytes(); self.send_response(200)
                    self.send_header('Content-Type','application/octet-stream'); self.send_header('Content-Encoding','gzip')
                    self.send_header('Cache-Control','public, max-age=86400, immutable')
                    self.send_header('Content-Length',str(len(body))); self.end_headers(); self.wfile.write(body); return
                if route.path not in ('/api/radar/v3/latest','/api/radar/v3/metadata','/api/radar/v3/frame','/api/radar/v3/frames'):
                    return self.reply(dict(error='Rota não encontrada'),404)
                radar, product = query.get('radar',[''])[0], query.get('product',['reflectivity'])[0]
                frames = store.frames(radar,product)
                for frame in frames:
                    if frame.get('kind')!='raster': frame['dataUrl'] = '/api/radar/v3/data?id='+frame['frameId']
                if route.path.endswith('/frames'):
                    return self.reply(dict(frames=[{k:v for k,v in f.items() if k not in ('azimuthStart','azimuthEnd')} for f in frames]))
                stamp = query.get('time',[None])[0]
                if stamp: frames = [f for f in frames if f['timestamp']==stamp]
                if not frames: return self.reply(dict(error='Velocidade Doppler indisponível para esta varredura.' if product=='velocity' else 'Refletividade indisponível para esta varredura.'),404)
                return self.reply(frames[-1])
            except ValueError as error: self.reply(dict(error=str(error)),400)
            except Exception:
                LOG.exception('[RADAR-ERROR] Falha na consulta'); self.reply(dict(error='Radar temporariamente indisponível'),503)

        def log_message(self, fmt, *args): LOG.info('[RADAR-METADATA] '+fmt,*args)
    return Handler

def main():
    logging.basicConfig(level=logging.INFO)
    store = Store(os.environ.get('RADAR_V3_INPUT','radar_v3_data'), os.environ.get('RADAR_V3_CACHE','radar_v3_cache'),cptec=True)
    feeds = os.environ.get('RADAR_V3_FEEDS')
    if feeds:
        from .ingest import poll_feeds
        threading.Thread(target=poll_feeds,args=(store.root,feeds),daemon=True).start()
    server = ThreadingHTTPServer((os.environ.get('HOST','127.0.0.1'),int(os.environ.get('PORT','8773'))),handler_for(store))
    LOG.info('Brasil Scope V3 iniciado'); server.serve_forever()

if __name__=='__main__': main()
